feature:
  - changed-files:
      - any-glob-to-any-file: ['src/**', 'docs/**']

bug:
  - changed-files:
      - any-glob-to-any-file: ['src/**']

chore:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'tests/**']

refactor:
  - changed-files:
      - any-glob-to-any-file: ['src/**']
