sonar.projectKey=address_engine
sonar.projectName=Address Engine
sonar.projectVersion=1.0

# Укажи свой org (для SonarCloud)
sonar.organization=your-org

# Пути к коду и тестам
sonar.sources=src
sonar.tests=tests,tests_full
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

# Исключаем папки
sonar.exclusions=vendor/**,build/**,docs/**
