name: PHP Tests & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: build/logs/clover.xml
          flags: unittests
          fail_ci_if_error: true


  behat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, sqlite, pdo_sqlite

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run Behat BDD tests
        run: vendor/bin/behat --format=allure --out=build/allure-results --strict --no-interaction


      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results


  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml --log-junit build/logs/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
